# Generated by Django 3.2.6 on 2021-09-16 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('screenshot', models.ImageField(default='https://via.placeholder.com/500x500.png?text=Default', upload_to='contact\\images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='project/images'),
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('remarks', models.CharField(max_length=200)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project')),
            ],
            options={
                'verbose_name': 'Remarks',
                'verbose_name_plural': 'Remarks',
            },
        ),
    ]
